### ISSUE TITLE
As a developer I want basic documentation on how Polaris does styling

### ISSUE THREAD

**Issue by AlanSl** [nearform/polaris#76]
Doesn't need to be long and should only have very simple code examples, mostly we just want to document anything surprising or non-obvious, particularly, known limitations and reasons behind decisions.

Could include:

- [x] State that we use Styled Components for web and native 
  - [x] Links to Styled Components web and native docs
  - [x] Say why we chose this - so future contributors don't think "Hey we should use Emotion instead" then repeat the same problems we've found
- [x] State what we're using for breakpoints / media queries
  - [x] Link to docs
  - [x] State known limitations (e.g. on Native)
- [x] State how different themes are used and how to switch themes in a component

**Comment by skywickenden** [comment]
Hey @AlanSl I'm back on the bench and just about to get to this. Can you remember why we didn't use Emotion. I remember we tried it and there were issues but I can't remember what they were?

**Comment by hizo** [comment]
Think it was mostly just the preference for `styled-components` because of better interpretation inside template literals, nothing major though. We wanted to switch to Emotion because it provided the same API and I had better experience with it in the past performance-wise, but these differences were probably solved in the in the latest versions.

**Comment by skywickenden** [comment]
Thanks Peter

**Comment by simoneb** [comment]
Closed by https://github.com/nearform/polaris/pull/109
